# Generated by Django 4.2.4 on 2023-12-20 14:42

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("socialaccount", "0003_extra_data_default_dict"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxySocialAccount",
            fields=[],
            options={
                "verbose_name": "Social Account",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("socialaccount.socialaccount",),
        ),
        migrations.CreateModel(
            name="ProxySocialApp",
            fields=[],
            options={
                "verbose_name": "Social App",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("socialaccount.socialapp",),
        ),
        migrations.CreateModel(
            name="ProxySocialToken",
            fields=[],
            options={
                "verbose_name": "Social Token",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("socialaccount.socialtoken",),
        ),
    ]
