# Generated by Django 4.2.11 on 2024-12-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("infocore", "0005_marketcode_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeServerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="Server check start time"),
                ),
                ("end_time", models.DateTimeField(help_text="Server check end time")),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Optional message describing the downtime",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "market_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_statuses",
                        to="infocore.marketcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Server Status",
                "verbose_name_plural": "Exchange Server Statuses",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="exchangeserverstatus",
            constraint=models.UniqueConstraint(
                fields=("market_code",), name="unique_market_code_status"
            ),
        ),
    ]
