services:

  nginx:
    image: community-nginx:latest
    build:
      context: "nginx/"
    container_name: community-nginx
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - drf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - community-network
    restart: always

  drf:
    image: community-drf:latest
    build:
      context: "community_drf/"
    container_name: community-drf
    volumes:
      - type: bind
        source: /opt/community_drf/media
        target: /opt/community_drf/media
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - community-network
    restart: always
  
networks:
  community-network:
    driver: bridge