# Generated by Django 4.2.11 on 2024-05-21 03:50

import django.core.validators
from django.db import migrations, models


def migrate_message_type(apps, schema_editor):
    """
    We can't import the Message model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Message = apps.get_model("messagecore", "Message")

    for message in Message.objects.all():
        message.type = message.type.upper()
        message.save()


class Migration(migrations.Migration):
    dependencies = [
        ("messagecore", "0003_message_read_alter_message_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="send_term",
            field=models.IntegerField(
                default=1,
                help_text="The interval between messages if sent more than 1 time\n(in seconds)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="send_times",
            field=models.IntegerField(
                default=1,
                help_text="Number of times the message should be sent",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("INFO", "INFO"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                    ("MONITOR", "MONITOR"),
                    ("TRADE", "TRADE"),
                ],
                default="INFO",
            ),
        ),
        migrations.RunPython(migrate_message_type),
    ]
