# Generated by Django 4.2.11 on 2024-12-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "messagecore",
            "0004_alter_message_send_term_alter_message_send_times_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("INFO", "INFO"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                    ("MONITOR", "MONITOR"),
                    ("TRADE", "TRADE"),
                    ("COMMAND", "COMMAND"),
                ],
                default="INFO",
            ),
        ),
    ]
