# Generated by Django 4.2.11 on 2024-07-24 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0002_postimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[("LIKE", "LIKE"), ("DISLIKE", "DISLIKE")],
                        default="LIKE",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date updated"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="board.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comment Reactions",
            },
        ),
        migrations.CreateModel(
            name="PostReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[("LIKE", "LIKE"), ("DISLIKE", "DISLIKE")],
                        default="LIKE",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date updated"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="board.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post Reactions",
            },
        ),
        migrations.DeleteModel(
            name="PostLikes",
        ),
        migrations.AddConstraint(
            model_name="postreactions",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_reactions__post__user"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentreactions",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="unique_reactions__comment__user"
            ),
        ),
    ]
