# Generated by Django 4.2.11 on 2024-07-26 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_categories(apps, schema_editor):
    """
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    categories = [
        "Announcement",
        "Freewriting",
        "Question",
        "Investment Strategy",
        "Information",
    ]
    Post = apps.get_model("board", "Post")
    for post in Post.objects.all():
        post.category = (
            post.category.name if post.category.name in categories else "Freewriting"
        )
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0003_commentreactions_postreactions_delete_postlikes_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
        migrations.RemoveConstraint(
            model_name="commentreactions",
            name="unique_reactions__comment__user",
        ),
        migrations.RemoveConstraint(
            model_name="postreactions",
            name="unique_reactions__post__user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_authored_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commentreactions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_comment_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Announcement", "Announcement"),
                    ("Freewriting", "Freewriting"),
                    ("Question", "Question"),
                    ("Investment Strategy", "Investment Strategy"),
                    ("Information", "Information"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_authored_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postreactions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="postviews",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_viewed_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="commentreactions",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"),
                name="unique__comment_reactions__comment__user",
            ),
        ),
        migrations.AddConstraint(
            model_name="postreactions",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique__post_reactions__post__user"
            ),
        ),
        migrations.DeleteModel(
            name="PostCategory",
        ),
    ]
