# Generated by Django 4.2.11 on 2024-07-26 09:18

from django.conf import settings
from django.db import migrations


def migrate_categories(apps, schema_editor):
    """
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    categories = {
        "1": "Announcement",
        "2": "Freewriting",
        "3": "Question",
        "4": "Investment Strategy",
        "5": "Information",
    }
    Post = apps.get_model("board", "Post")
    for post in Post.objects.all():
        post.category = (
            categories[post.category] if post.category in categories else "Freewriting"
        )
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "board",
            "0004_remove_commentreactions_unique_reactions__comment__user_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
        migrations.DeleteModel(
            name="PostCategory",
        ),
    ]
