# Generated by Django 4.2.4 on 2024-02-16 11:51

from django.db import migrations, models

from api.utils import get_api_permission_choices


def create_user_roles(apps, schema_editor):
    """
    We can't import the UserRole model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Permission = apps.get_model("api", "Permission")

    for codename, name in get_api_permission_choices():
        Permission.objects.create(name=name, codename=codename)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("codename", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "API Permission",
            },
        ),
        migrations.RunPython(create_user_roles),
    ]
