# Generated by Django 4.2.11 on 2024-03-07 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "upper_share_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(unique=True)),
                (
                    "target_market_code",
                    models.CharField(
                        choices=[
                            ("BINANCE_SPOT/USDT", "BINANCE_SPOT/USDT"),
                            ("BINANCE_USD_M/USDT", "BINANCE_USD_M/USDT"),
                            ("BINANCE_COIN_M/USD", "BINANCE_COIN_M/USD"),
                            ("UPBIT_SPOT/KRW", "UPBIT_SPOT/KRW"),
                            ("UPBIT_SPOT/BTC", "UPBIT_SPOT/BTC"),
                            ("BITHUMB_SPOT/KRW", "BITHUMB_SPOT/KRW"),
                            ("OKX_SPOT/USDT", "OKX_SPOT/USDT"),
                            ("OKX_USD_M/USDT", "OKX_USD_M/USDT"),
                            ("OKX_COIN_M/USD", "OKX_COIN_M/USD"),
                            ("BYBIT_SPOT/USDT", "BYBIT_SPOT/USDT"),
                            ("BYBIT_USD_M/USDT", "BYBIT_USD_M/USDT"),
                            ("BYBIT_COIN_M/USD", "BYBIT_COIN_M/USD"),
                        ],
                        max_length=150,
                        verbose_name="Target Market Code",
                    ),
                ),
                (
                    "origin_market_code",
                    models.CharField(
                        choices=[
                            ("BINANCE_SPOT/USDT", "BINANCE_SPOT/USDT"),
                            ("BINANCE_USD_M/USDT", "BINANCE_USD_M/USDT"),
                            ("BINANCE_COIN_M/USD", "BINANCE_COIN_M/USD"),
                            ("UPBIT_SPOT/KRW", "UPBIT_SPOT/KRW"),
                            ("UPBIT_SPOT/BTC", "UPBIT_SPOT/BTC"),
                            ("BITHUMB_SPOT/KRW", "BITHUMB_SPOT/KRW"),
                            ("OKX_SPOT/USDT", "OKX_SPOT/USDT"),
                            ("OKX_USD_M/USDT", "OKX_USD_M/USDT"),
                            ("OKX_COIN_M/USD", "OKX_COIN_M/USD"),
                            ("BYBIT_SPOT/USDT", "BYBIT_SPOT/USDT"),
                            ("BYBIT_USD_M/USDT", "BYBIT_USD_M/USDT"),
                            ("BYBIT_COIN_M/USD", "BYBIT_COIN_M/USD"),
                        ],
                        max_length=150,
                        verbose_name="Origin Market Code",
                    ),
                ),
                (
                    "max_depth",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "contact",
                    models.TextField(
                        blank=True, help_text="Telegram id or phone number", null=True
                    ),
                ),
                (
                    "referral_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referral.referralgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="referral_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "referral_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referral.referralcode",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
