# Generated by Django 4.2.11 on 2024-03-29 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referred_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="used_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="referralcode",
            name="max_depth",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="referralcode",
            name="origin_market_code",
            field=models.CharField(max_length=150, verbose_name="Origin Market Code"),
        ),
        migrations.AlterField(
            model_name="referralcode",
            name="target_market_code",
            field=models.CharField(max_length=150, verbose_name="Target Market Code"),
        ),
    ]
