# Generated by Django 4.2.11 on 2024-12-12 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliate",
            name="affiliate_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
