# Generated by Django 4.2.11 on 2024-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0004_affiliaterequest_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliaterequest",
            name="parent_affiliate_code",
            field=models.CharField(
                blank=True,
                help_text="Code of the parent affiliate",
                max_length=100,
                null=True,
            ),
        ),
    ]
