# Generated by Django 4.2.4 on 2023-10-24 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("icon", models.ImageField(upload_to="assets/icons/")),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
