# Generated by Django 4.2.4 on 2024-01-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infocore", "0003_alter_asset_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Market Code",
            },
        ),
    ]
