services:
  trade-postgres:
    container_name: test-trade-postgres
    volumes:
      - ${HOME}/test-trade-postgres/data/:/var/lib/postgresql/data/

  trade-core-api:
    image: trade-core-api:test
    container_name: test-trade-core-api
    volumes:
      - ${HOME}/test-trade-core-api/logs:/home/trade_core/trade_core/loggers/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trade-test-api.rule=Host(`test.arbicrypto.net`) && PathPrefix(`/trade-api/`)"
      - "traefik.http.routers.trade-test-api.entrypoints=websecure"
      - "traefik.http.routers.trade-test-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.trade-test-api.middlewares=trade-ip-allowlist@file"
      - "traefik.http.services.trade-test-api.loadbalancer.server.port=8000"

  trade-core:
    image: trade-core:test
    container_name: test-trade-core
    volumes:
      - ${HOME}/test-trade-core/logs:/home/trade_core/trade_core/loggers/logs

networks:
  trade-network:
    name: test-trade-network
  traefik-network:
    external: true

