version: '3'
services:

  nginx:
    image: community-nginx:test
    build:
      context: "nginx/"
    container_name: test-community-nginx
    volumes:
      - $HOME/test-community-nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - $HOME/test-community-nginx/certs/:/etc/ssl/certs/
      - $HOME/test-community-nginx/private/:/etc/ssl/private/
      - $HOME/test-community-web/build/:/opt/community_frontend/build/
    ports:
      - "20080:20080"
      - "20081:20081"
    depends_on:
      - drf
    networks:
      - test-community-network
    restart: always
  
  postgres:
    image: postgres:16rc1-alpine
    container_name: test-community-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_COMMUNITY}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - $HOME/test-community-postgres/data/:/var/lib/postgresql/data/
    ports:
      - "25432:5432"
    expose:
      - "5432"
    networks:
      - test-community-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  
  redis:
    image: redis:7-alpine
    container_name: test-community-redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - $HOME/test-community-redis/data/:/data/
      - $HOME/test-community-redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "26379:6379"
    expose:
      - "6379"
    networks:
      - test-community-network
    restart: always
  
  mongodb:
    image: mongo:6.0
    container_name: test-community-mongodb
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - $HOME/test-community-mongodb/data/:/data/
    ports:
      - "27018:27017"
    expose:
      - "27017"
    networks:
      - test-community-network
    restart: always

  drf:
    image: community-drf:test
    depends_on:
      postgres:
        condition: service_healthy
    container_name: test-community-drf
    volumes:
      - $HOME/test-community-drf/media:/home/django/community_drf/media
    expose:
      - "8000"
    networks:
      - test-community-network
    restart: always
  
  # news-core:
  #   image: news-core:test
  #   container_name: test-news-core
  #   networks:
  #     - test-community-network
  #   restart: always
  
networks:
  test-community-network:
    driver: bridge