version: '3'
services:
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - $HOME/certbot/conf:/etc/letsencrypt
      - $HOME/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: community-nginx
    build:
      context: "nginx/"
    container_name: prod-community-nginx
    volumes:
      - $HOME/prod-community-web/build/:/opt/community_frontend/build/
      - $HOME/prod-community-drf/static/:/opt/community_drf/static/
      - $HOME/prod-community-drf/media/:/opt/community_drf/media/
      - $HOME/certbot/conf:/etc/letsencrypt
      - $HOME/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - drf
    networks:
      - prod-community-network
    restart: always
  
  postgres:
    image: postgres:16rc1-alpine
    container_name: prod-community-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_COMMUNITY}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - $HOME/prod-community-postgres/data/:/var/lib/postgresql/data/
    expose:
      - "5432"
    networks:
      - prod-community-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  
  redis:
    image: redis:7-alpine
    container_name: prod-community-redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - $HOME/prod-community-redis/data/:/data/
      - $HOME/prod-community-redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - prod-community-network
    restart: always
  
  mongodb:
    image: mongo:6.0
    container_name: prod-community-mongodb
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - $HOME/prod-community-mongodb/data/:/data/
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - prod-community-network
    restart: always
  
  drf:
    image: community-drf
    depends_on:
      postgres:
        condition: service_healthy
    container_name: prod-community-drf
    volumes:
      - $HOME/prod-community-drf/static:/home/django/community_drf/static
      - $HOME/prod-community-drf/media:/home/django/community_drf/media
    expose:
      - "8000"
    networks:
      - prod-community-network
    restart: always
  
  news-core:
    image: news-core
    container_name: prod-news-core
    networks:
      - prod-community-network
    restart: always
  
  info-core:
    image: info-core
    container_name: prod-info-core
    networks:
      - prod-community-network
    restart: always

networks:
  prod-community-network:
    driver: bridge