# Generated by Django 4.2.4 on 2023-12-14 19:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("domain", models.CharField(max_length=200)),
                (
                    "port",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                ("telegram_bot_id", models.CharField(max_length=50)),
                ("telegram_bot_token", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_expiry_date",
                    models.DateTimeField(
                        help_text="If a user makes a payment for the subscription, the `service_expiry_date` will be extended."
                    ),
                ),
                (
                    "addcir_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="A number that should be applied in the Arbot core when it runs the addcir feature.<br>Format: `000.0000`",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "addcir_num_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="A number that should be applied in the Arbot core when it runs the addcir feature.",
                        null=True,
                    ),
                ),
                (
                    "binance_leverage",
                    models.IntegerField(
                        default=4,
                        help_text="Leverage to use when executing trades in Binance.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "binance_cross",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Binance Margin mode is cross (or isolated).",
                    ),
                ),
                (
                    "risk_warning_mode",
                    models.IntegerField(
                        choices=[
                            (0, "Disabled"),
                            (1, "Send warning"),
                            (2, "Send warning and exit entered trades"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "risk_warning_threshold_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="If the unrealized loss goes below the risk warning threshold, risk warning function is getting executed according to the setting. <br>`risk_warning_threshold_p` value should be set to *less than 0*. But when it's set to `null`, it has a special meaning.<br>`null`: When margin_call signal is sent",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(0)],
                    ),
                ),
                (
                    "safe_reverse",
                    models.BooleanField(
                        default=True, help_text="Whether to turn on reverse trade."
                    ),
                ),
                (
                    "alarm_num",
                    models.IntegerField(
                        default=1,
                        help_text="When a user receives a telegram message from the telegram bot, a user can configure the bot to send more than one message about the same event so that a user (e.g. sleeping) can be alarmed enough.",
                    ),
                ),
                (
                    "alarm_term_sec",
                    models.IntegerField(
                        default=1,
                        help_text="Related to the alarm_num. A user can also configure the term between messages if the user has set the alarm_num bigger than 1.",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="This is the server where the user's trade settings will be executed.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="user_configs",
                        to="tradecore.node",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
