# Generated by Django 4.2.4 on 2023-12-18 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userconfig",
            options={"verbose_name": "User Config"},
        ),
        migrations.RemoveField(
            model_name="userconfig",
            name="node",
        ),
    ]
