# Generated by Django 4.2.4 on 2024-01-11 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0002_alter_userconfig_options_remove_userconfig_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="url",
            field=models.CharField(
                default="http://localhost:8000",
                max_length=200,
                validators=[django.core.validators.URLValidator()],
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserConfig",
        ),
    ]
