# Generated by Django 4.2.4 on 2024-01-11 08:33

from django.db import migrations


def make_url(apps, schema_editor):
    """
    We can't import the Node model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Node = apps.get_model("tradecore", "Node")
    for node in Node.objects.all():
        node.url = f"{node.domain}:{node.port}"
        node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0003_node_url_delete_userconfig"),
    ]

    operations = [
        migrations.RunPython(make_url),
    ]
