# Generated by Django 4.2.4 on 2024-01-11 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0004_migrate_domain_port_to_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="node",
            name="port",
        ),
        migrations.RemoveField(
            model_name="node",
            name="telegram_bot_id",
        ),
        migrations.RemoveField(
            model_name="node",
            name="telegram_bot_token",
        ),
    ]
