# Generated by Django 4.2.4 on 2024-02-02 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("infocore", "0004_marketcode"),
        ("tradecore", "0005_remove_node_domain_remove_node_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="max_user_count",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="node",
            name="users",
            field=models.ManyToManyField(
                related_name="nodes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="url",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.URLValidator()],
                verbose_name="URL",
            ),
        ),
        migrations.CreateModel(
            name="TradeConfigAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_market_code",
                    models.CharField(max_length=150, verbose_name="Target Market Code"),
                ),
                (
                    "origin_market_code",
                    models.CharField(max_length=150, verbose_name="Origin Market Code"),
                ),
                (
                    "trade_config_uuid",
                    models.UUIDField(
                        help_text="Trade config uuid from trade_core",
                        verbose_name="Trade Config UUID",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trade_config_allocations",
                        to="tradecore.node",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trade_config_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Config Allocation",
            },
        ),
        migrations.CreateModel(
            name="NodeMarketCodeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_code_services",
                        to="tradecore.node",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="origin",
                        to="infocore.marketcode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="target",
                        to="infocore.marketcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node MarketCode Service",
            },
        ),
        migrations.AddConstraint(
            model_name="tradeconfigallocation",
            constraint=models.UniqueConstraint(
                fields=("user", "target_market_code", "origin_market_code"),
                name="unique__user__target__origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="nodemarketcodeservice",
            constraint=models.UniqueConstraint(
                fields=("node", "target", "origin"), name="unique__node__target__origin"
            ),
        ),
    ]
