# Generated by Django 4.2.11 on 2024-03-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infocore", "0004_marketcode"),
        ("tradecore", "0006_node_max_user_count_node_users_alter_node_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnabledMarketCodeCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_support", models.BooleanField(default=False)),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin",
                        to="infocore.marketcode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target",
                        to="infocore.marketcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enabled Market Code Combination",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="market_code_combinations",
            field=models.ManyToManyField(
                blank=True, to="tradecore.enabledmarketcodecombination"
            ),
        ),
        migrations.AddConstraint(
            model_name="enabledmarketcodecombination",
            constraint=models.UniqueConstraint(
                fields=("target", "origin"), name="unique__target__origin"
            ),
        ),
    ]
