# Generated by Django 4.2.4 on 2023-12-22 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("telegram_bot_name", models.CharField(max_length=150)),
                ("telegram_chat_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField(null=True)),
                ("remarks", models.CharField(max_length=300, null=True)),
                ("origin", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("error", "Error"),
                            ("monitor", "Monitor"),
                            ("trade", "Trade"),
                        ],
                        default="info",
                    ),
                ),
                ("code", models.IntegerField(null=True)),
                ("sent", models.BooleanField(default=False)),
                ("send_count", models.IntegerField(default=1)),
            ],
        ),
    ]
