# Generated by Django 4.2.4 on 2024-01-05 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagecore", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="telegram_bot_name",
            new_name="telegram_bot_username",
        ),
        migrations.RemoveField(
            model_name="message",
            name="send_count",
        ),
        migrations.AddField(
            model_name="message",
            name="send_term",
            field=models.IntegerField(
                default=1,
                help_text="Term between the repeating message in seconds",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="send_times",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
