# Generated by Django 4.2.4 on 2024-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "messagecore",
            "0002_rename_telegram_bot_name_message_telegram_bot_username_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="remarks",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("monitor", "Monitor"),
                    ("trade", "Trade"),
                ],
                default="info",
            ),
        ),
    ]
