# Generated by Django 4.2.11 on 2026-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messagecore", "0005_alter_message_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["telegram_bot_username", "sent"], name="idx_msg_bot_sent"
            ),
        ),
    ]
