upstream docker-drf {
    server drf:8000;
}

server {
    listen 20080;
    server_name localhost;

    root /opt/community_frontend/build;
}


server {
    listen 20081;

    location / {
        proxy_pass http://docker-drf/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect off;
    }
}