# Generated by Django 4.2.4 on 2023-10-11 09:37

import django.core.validators
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbot", "0002_alter_arbotnode_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="addcir_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="A number that should be applied in the Arbot core when it runs the addcir feature.<br>Format: `000.0000`",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="addcir_num_limit",
            field=models.IntegerField(
                blank=True,
                help_text="A number that should be applied in the Arbot core when it runs the addcir feature.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="alarm_num",
            field=models.IntegerField(
                default=1,
                help_text="When a user receives a telegram message from the telegram bot, a user can configure the bot to send more than one message about the same event so that a user (e.g. sleeping) can be alarmed enough.",
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="alarm_term_sec",
            field=models.IntegerField(
                default=1,
                help_text="Related to the alarm_num. A user can also configure the term between messages if the user has set the alarm_num bigger than 1.",
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="binance_cross",
            field=models.BooleanField(
                default=False,
                help_text="Whether Binance Margin mode is cross (or isolated).",
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="binance_leverage",
            field=models.IntegerField(
                default=4,
                help_text="Leverage to use when executing trades in Binance.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="node",
            field=models.ForeignKey(
                help_text="This is the server where the user's' trade settings will be executed.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="user_configs",
                to="arbot.arbotnode",
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="risk_warning_mode",
            field=models.IntegerField(
                choices=[
                    (0, "Disabled"),
                    (1, "Send warning"),
                    (2, "Send warning and exit entered trades"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="risk_warning_threshold_p",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="If the unrealized loss goes below the risk warning threshold, risk warning function is getting executed according to the setting. <br>`risk_warning_threshold_p` value should be set to *less than 0*. But when it's set to `null`, it has a special meaning.<br>`null`: When margin_call signal is sent",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MaxValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="safe_reverse",
            field=models.BooleanField(
                default=True, help_text="Whether to turn on reverse trade."
            ),
        ),
        migrations.AlterField(
            model_name="arbotuserconfig",
            name="service_expiry_date",
            field=models.DateTimeField(
                help_text="If a user makes a payment for the subscription, the `service_expiry_date` will be extended."
            ),
        ),
    ]
