# Generated by Django 4.2.4 on 2023-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infocore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="note",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
