# Generated by Django 4.2.4 on 2023-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infocore", "0002_asset_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
