# Generated by Django 4.2.11 on 2024-03-18 09:50

from django.db import migrations, models


def set_type_to_existing_market_codes(apps, schema_editor):
    """Importing the class to use the static function"""
    from infocore.models import MarketCode as MarketCodeClass

    """
    We can't import the MarketCode "model" itself directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    MarketCode = apps.get_model("infocore", "MarketCode")

    for market_code in MarketCode.objects.all():
        market_code.type = MarketCodeClass.get_type(market_code.code)
        market_code.save()


class Migration(migrations.Migration):
    dependencies = [
        ("infocore", "0004_marketcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketcode",
            name="type",
            field=models.CharField(
                choices=[
                    ("SPOT", "SPOT"),
                    ("USD_M", "USD_M"),
                    ("COIN_M", "COIN_M"),
                    ("FUTURES", "FUTURES"),
                ],
                default="SPOT",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_type_to_existing_market_codes),
    ]
