# Generated by Django 4.2.11 on 2025-12-24 05:30
# This migration was recreated to match the database state

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infocore', '0005_marketcode_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market_code', models.CharField(help_text="Target market code, e.g., 'UPBIT_SPOT/KRW'", max_length=150)),
                ('origin_market_code', models.CharField(help_text="Origin market code, e.g., 'BINANCE_USD_M/USDT'", max_length=150)),
                ('base_assets', models.JSONField(blank=True, help_text='List of base assets to monitor, e.g., ["BTC", "ETH"]. Leave empty to monitor all assets in the market combination.', null=True)),
                ('volatility_threshold', models.DecimalField(decimal_places=6, help_text='Trigger notification when mean_diff >= this value. Example: 0.05 means 5% volatility.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notification_interval_minutes', models.PositiveIntegerField(default=180, help_text='Minimum minutes between notifications for this config.', validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volatility_notification_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volatility Notification Config',
                'verbose_name_plural': 'Volatility Notification Configs',
            },
        ),
        migrations.AddConstraint(
            model_name='volatilitynotificationconfig',
            constraint=models.UniqueConstraint(fields=('user', 'target_market_code', 'origin_market_code'), name='unique_user_market_combination'),
        ),
    ]
