# Generated by Django 4.2.11 on 2025-12-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infocore', '0006_volatilitynotificationconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volatilitynotificationconfig',
            name='last_notified_at',
        ),
        migrations.CreateModel(
            name='VolatilityNotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_asset', models.CharField(max_length=30)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('mean_diff', models.DecimalField(decimal_places=6, help_text='The volatility value when notification was sent.', max_digits=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to='infocore.volatilitynotificationconfig')),
            ],
            options={
                'verbose_name': 'Volatility Notification History',
                'verbose_name_plural': 'Volatility Notification Histories',
                'indexes': [models.Index(fields=['config', 'base_asset', 'notified_at'], name='infocore_vo_config__26a828_idx')],
            },
        ),
    ]
