# Generated by Django 4.2.4 on 2023-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("visitor", "Visitor"),
                    ("user", "User"),
                    ("internal", "Internal"),
                ],
                default="visitor",
            ),
        ),
    ]
