# Generated by Django 4.2.4 on 2023-10-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userblocklist_unique__target_email__target_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userblocklist",
            name="target_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="username"
            ),
        ),
    ]
