# Generated by Django 4.2.4 on 2023-12-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0001_initial"),
        ("users", "0008_remove_userblocklist_target_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="telegram_id",
            new_name="telegram_chat_id",
        ),
        migrations.AddField(
            model_name="user",
            name="node",
            field=models.ForeignKey(
                help_text="Node where the user transactions are processed",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="tradecore.node",
            ),
        ),
        migrations.AlterField(
            model_name="userblocklist",
            name="target_username",
            field=models.CharField(max_length=100, verbose_name="username"),
        ),
    ]
