# Generated by Django 4.2.4 on 2024-01-31 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_usersocialapps_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersocialapps",
            options={"verbose_name": "User Social App"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="node",
        ),
    ]
