# Generated by Django 4.2.4 on 2024-02-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_create_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Management",
                "verbose_name_plural": "User Management",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="managers",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default="VISITOR",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.userrole",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="UUID"
            ),
        ),
        migrations.DeleteModel(
            name="UserManagers",
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="managed_user",
            field=models.ForeignKey(
                db_column="managed_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="manager",
            field=models.ForeignKey(
                db_column="manager_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
