# Generated by Django 4.2.11 on 2024-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_deposithistory_depositbalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="referral",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="username"
            ),
        ),
    ]
