# Generated by Django 4.2.11 on 2024-04-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_userprofile_referral_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposithistory",
            name="change",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
