# Generated by Django 4.2.11 on 2024-05-17 03:41

from django.db import migrations, models


def migrate_deposithistory_type(apps, schema_editor):
    """
    We can't import the DepositHistory model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    DepositHistory = apps.get_model("users", "DepositHistory")

    for deposit_history in DepositHistory.objects.all():
        deposit_history.type = deposit_history.type.upper()
        deposit_history.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_deposithistory_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposithistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("WITHDRAW", "WITHDRAW"),
                    ("DEPOSIT", "DEPOSIT"),
                    ("COMMISSION", "COMMISSION"),
                    ("FEE", "FEE"),
                    ("TRANSFER", "TRANSFER"),
                    ("COUPON", "COUPON"),
                ]
            ),
        ),
        migrations.RunPython(migrate_deposithistory_type),
    ]
