# Generated by Django 4.2.11 on 2024-12-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_userauthlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposithistory",
            name="commission_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_history_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPOSIT", "DEPOSIT"), ("COMMISSION", "COMMISSION")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "requested_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_datetime", models.DateTimeField(blank=True, null=True)),
                ("completed_datetime", models.DateTimeField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Request",
                "verbose_name_plural": "Withdrawal Requests",
            },
        ),
    ]
