# Generated by Django 4.2.11 on 2024-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_remove_deposithistory_coupon_redemption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposithistory",
            name="commission_from",
        ),
        migrations.AddField(
            model_name="deposithistory",
            name="referral_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="deposithistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("WITHDRAW", "WITHDRAW"),
                    ("DEPOSIT", "DEPOSIT"),
                    ("FEE", "FEE"),
                    ("TRANSFER", "TRANSFER"),
                    ("COUPON", "COUPON"),
                ]
            ),
        ),
    ]
