# Generated by Django 4.2.11 on 2024-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0003_affiliaterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliaterequest",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Contact details of the user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliaterequest",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the user's platform and how they plan to promote us",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliaterequest",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="URL of the user's website or social media profile",
                null=True,
            ),
        ),
    ]
