# Generated by Django 4.2.11 on 2024-12-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0005_affiliaterequest_parent_affiliate_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of service for which commission is earned",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMMISSION", "COMMISSION"),
                            ("WITHDRAW", "WITHDRAW"),
                            ("TRANSFER", "TRANSFER"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trade_uuid", models.UUIDField()),
                ("change", models.DecimalField(decimal_places=8, max_digits=20)),
                ("balance", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_history",
                        to="referral.affiliate",
                    ),
                ),
                (
                    "child_affiliate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_commission_history",
                        to="referral.affiliate",
                    ),
                ),
                (
                    "user_who_paid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission History",
                "verbose_name_plural": "Commission History",
            },
        ),
        migrations.CreateModel(
            name="CommissionBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "affiliate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_balance",
                        to="referral.affiliate",
                    ),
                ),
            ],
        ),
    ]
