# Generated by Django 4.2.11 on 2024-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0006_commissionhistory_commissionbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionhistory",
            name="trade_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the trade for which commission is earned",
                null=True,
            ),
        ),
    ]
