# Generated by Django 4.2.4 on 2023-11-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("url", models.CharField(max_length=500)),
                ("thumbnail", models.CharField(max_length=500)),
                ("media", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "news",
                "managed": False,
            },
        ),
    ]
