# Generated by Django 4.2.4 on 2023-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newscore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("url", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "announcements",
                "managed": False,
            },
        ),
    ]
