# Generated by Django 4.2.4 on 2023-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newscore", "0002_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("extra_data", models.JSONField()),
                ("datetime", models.DateTimeField()),
                ("url", models.CharField(max_length=500)),
                ("social_media", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "posts",
                "managed": False,
            },
        ),
    ]
