# Generated by Django 4.2.4 on 2023-09-27 03:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoriteAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_asset", models.CharField(max_length=10)),
                (
                    "market_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150), size=None
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User favorite assets",
            },
        ),
        migrations.DeleteModel(
            name="UserFavoriteSymbols",
        ),
        migrations.AddConstraint(
            model_name="userfavoriteassets",
            constraint=models.UniqueConstraint(
                fields=("user", "market_codes", "base_asset"),
                name="unique__user__base_asset__market_codes",
            ),
        ),
    ]
