# Generated by Django 4.2.4 on 2023-10-13 06:45

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userfavoriteassets_delete_userfavoritesymbols_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlocklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("target_ip", models.CharField(max_length=200)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "User blocklist",
            },
        ),
        migrations.AddConstraint(
            model_name="userblocklist",
            constraint=models.UniqueConstraint(
                fields=("target_email", "target_ip"),
                name="unique__target_email__target_ip",
            ),
        ),
    ]
