# Generated by Django 4.2.4 on 2023-10-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userblocklist_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userblocklist",
            name="unique__target_email__target_ip",
        ),
        migrations.AlterField(
            model_name="userblocklist",
            name="target_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
    ]
