# Generated by Django 4.2.4 on 2023-10-20 04:23

from django.db import migrations


def generate_username(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserBlocklist = apps.get_model("users", "UserBlocklist")

    for row in UserBlocklist.objects.all():
        try:
            row.target_username = User.objects.get(email=row.target_email).username
        except User.DoesNotExist:
            row.target_username = row.target_ip

        row.save(update_fields=["target_username"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userblocklist_target_username"),
    ]

    operations = [
        migrations.RunPython(generate_username, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userblocklist",
            name="target_email",
        ),
    ]
