# Generated by Django 4.2.4 on 2023-12-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0002_alter_userconfig_options_remove_userconfig_node"),
        ("users", "0009_rename_telegram_id_user_telegram_chat_id_user_node_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="userblocklist",
            options={
                "verbose_name": "User Blocklist",
                "verbose_name_plural": "User Blocklist",
            },
        ),
        migrations.AlterModelOptions(
            name="userfavoriteassets",
            options={
                "verbose_name": "User Favorite Assets",
                "verbose_name_plural": "User Favorite Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="usermanagers",
            options={"verbose_name": "User Manager"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "User Profile"},
        ),
        migrations.AlterField(
            model_name="user",
            name="node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node where the user's trades are executed",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="users",
                to="tradecore.node",
            ),
        ),
    ]
