# Generated by Django 4.2.4 on 2023-12-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("socialaccounts", "0001_initial"),
        ("users", "0010_alter_user_options_alter_userblocklist_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialApps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "socialapp",
                    models.ForeignKey(
                        help_text="The Telegram bot to allocate to the user.<br><em>The social apps available currently are telegram bots.<br>Google is also available, but is used for login.</em>",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="users",
                        to="socialaccounts.proxysocialapp",
                        verbose_name="social app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socialapps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Social Apps",
            },
        ),
        migrations.AddConstraint(
            model_name="usersocialapps",
            constraint=models.UniqueConstraint(
                fields=("socialapp", "user"), name="unique__socialapp__user"
            ),
        ),
    ]
