# Generated by Django 4.2.4 on 2024-02-22 11:07

from django.db import migrations, models


def create_user_roles(apps, schema_editor):
    """
    We can't import the UserRole model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    UserRole = apps.get_model("users", "UserRole")

    """ But this one is fine since we are just accessing Roles """
    from users.models import UserRole as ClassUserRole

    for name, desc in ClassUserRole.Roles:
        UserRole.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("users", "0012_alter_usersocialapps_options_remove_user_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ADMIN"),
                            ("INTERNAL", "INTERNAL"),
                            ("MANAGER", "MANAGER"),
                            ("AFFILIATE", "AFFILIATE"),
                            ("USER", "USER"),
                            ("VISITOR", "VISITOR"),
                        ],
                        default="VISITOR",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="<em>API permissions for <b>VISITORS</b> and <b>USERS</b> are not customizable.</em><br>",
                        null=True,
                        to="api.permission",
                        verbose_name="API Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
            },
        ),
        migrations.RunPython(create_user_roles),
    ]
