# Generated by Django 4.2.11 on 2024-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_deposithistory_commission_from_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposithistory",
            name="trade_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
