# Generated by Django 4.2.11 on 2024-12-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0002_alter_coupon_code"),
        ("users", "0021_deposithistory_trade_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposithistory",
            name="coupon_redemption",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposit_history",
                to="coupon.couponredemption",
            ),
        ),
    ]
