# Generated by Django 4.2.11 on 2026-03-18 07:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_remove_deposithistory_commission_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposithistory",
            name="txid",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="deposithistory",
            name="type",
            field=models.CharField(
                choices=[
                    ("WITHDRAW", "WITHDRAW"),
                    ("DEPOSIT", "DEPOSIT"),
                    ("COMMISSION", "COMMISSION"),
                    ("FEE", "FEE"),
                    ("TRANSFER", "TRANSFER"),
                    ("COUPON", "COUPON"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
