# Generated by Django 4.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_deposithistory_txid_alter_deposithistory_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_nickname",
            field=models.CharField(
                blank=True,
                help_text="Unique display name for the chat. 2-20 chars, starts with a letter.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="chat nickname",
            ),
        ),
    ]
