upstream docker-drf {
    server drf:8000;
}

server {
    listen 80;
    server_name acw-test.orbitholdings.org;

    # Serve the ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all other HTTP requests to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name acw-test.orbitholdings.org;

    client_max_body_size 100M;

    gzip on;
    gzip_disable "msie6";
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/x-javascript text>
    gzip_comp_level 6;

    root /opt/community_frontend/build;

    location / {
        try_files $uri$args $uri$args/ /index.html;
    }

    location /api/ {
        proxy_pass http://docker-drf/api/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        # websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # proxy_redirect off;
    }

    location /api/static/ {
        alias /opt/community_drf/static/;
        autoindex off;
    }

    location /api/media/ {
        alias /opt/community_drf/media/;
        autoindex off;
    }

    ssl_certificate /etc/letsencrypt/live/acw-test.orbitholdings.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/acw-test.orbitholdings.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}