"""
Django settings for community_drf project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import dj_database_url
import os

from datetime import timedelta
from django.utils.translation import gettext_lazy as _
from environ import Env
from os.path import join
from pathlib import Path
from urllib.parse import urljoin

from .spectacular import *  # noqa
from .unfold import *  # noqa

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env(DEBUG=(bool, False))

# Take environment variables from .env file
Env.read_env(os.path.join(Path(BASE_DIR).parent, ".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

X_FRAME_OPTIONS = "SAMEORIGIN"

SILENCED_SYSTEM_CHECKS = ["security.W019"]

# Application definition

# Manually setting SCRIPT_NAME in urls because
# FORCE_SCRIPT_NAME doesn't work on admin urls
SCRIPT_NAME = env("DJANGO_SCRIPT_NAME", default="")

SITE_ID = 2

ROOT_URLCONF = "config.urls"

ASGI_APPLICATION = "config.asgi.application"

WSGI_APPLICATION = "config.wsgi.application"

DJANGO_APPS = (
    "daphne",
    "unfold",
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
)

THIRD_PARTY_APPS = (
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.telegram",
    "django_celery_beat",
    "django_celery_results",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "django_filters",
    "django_rq",
    "drf_spectacular",
    "channels",
)

LOCAL_APPS = (
    "main",
    "api",
    "authentication",
    "board",
    "chat",
    "fee",
    "socialaccounts",
    "referral",
    "users",
    "infocore",
    "messagecore",
    "newscore",
    "tradecore",
    "wallet",
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Used in api app and permission system
API_APP_SETTINGS = {
    "PUBLIC": ["authentication", "chat", "infocore", "newscore"],
    "INTERNAL": ["schema", "redoc", "swagger"],  # for internal users only
    "PROTECTED": ["tradecore", "messagecore"],  # on permission basis
}

MIDDLEWARE = (
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
)

#############
# DATABASES #
#############
DATABASES = {
    "default": dj_database_url.config(
        default=env("COMMUNITY_DB_URL"),
    ),
    "newscore": dj_database_url.config(
        default=env("NEWSCORE_DB_URL"),
    ),
    "messagecore": dj_database_url.config(
        default=env("MESSAGECORE_DB_URL"),
    ),
}

DATABASE_ROUTERS = ["config.dbrouter.DBRouter"]

# MONGODB
MONGODB = {
    "HOST": env("MONGODB_HOST", default="mongodb"),
    "PORT": env.int("MONGODB_PORT", default=27017),
    "USERNAME": env("MONGODB_USERNAME", default=""),
    "PASSWORD": env("MONGODB_PASSWORD", default=""),
}

MONGO_CHAT_DB = "ACW_USER_CHAT"

# CACHE
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_DB_URL", default="redis://localhost:6379"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# REDIS QUEUE
RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
    },
}

RQ_SHOW_ADMIN_LINK = True

# DJANGO CHANNELS
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": env(
                        "REDIS_DB_URL",
                        default="redis://localhost:6379",
                    ),
                    "client_name": "django-channels",
                }
            ],
        },
    },
}

REDIS_CHAT_BLOCKLIST_KEY = "acw:user:blocklist"

# CELERY

CELERY_BROKER_URL = env("REDIS_DB_URL", default="redis://localhost:6379")

CELERY_RESULT_BACKEND = "django-db"

CELERY_CACHE_BACKEND = "default"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "JWT_AUTH_RETURN_EXPIRATION": True,
    "JWT_AUTH_COOKIE": "drf-auth",
    "JWT_AUTH_REFRESH_COOKIE": "drf-refresh",
    "USER_DETAILS_SERIALIZER": "users.serializers.UserSerializer",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# django-allauth config
ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"

ACCOUNT_AUTHENTICATION_METHOD = "username_email"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.normpath(os.path.join(os.path.dirname(BASE_DIR), "static"))

STATIC_URL = urljoin(SCRIPT_NAME, "static/")

MEDIA_ROOT = join(os.path.dirname(BASE_DIR), "media")

MEDIA_URL = urljoin(SCRIPT_NAME, "media/")

TEMPLATES_DIRS = ["templates"]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": TEMPLATES_DIRS,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

FIXTURE_DIRS = [os.path.normpath(os.path.join(os.path.dirname(BASE_DIR), "fixtures"))]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("ko", _("Korean")),
]

LOCALE_PATHS = [
    join(Path(BASE_DIR).parent.absolute(), "locale"),
]

# CORE
CORE_IPS = env.list("CORE_IPS", default=[])

# CoinMarketCap
COINMARKETCAP_API_KEY = env("COINMARKETCAP_API_KEY")
COINMARKETCAP_API_URL = "https://pro-api.coinmarketcap.com/v2"
COINMARKETCAP_CRYPTO_INFO_API = f"{COINMARKETCAP_API_URL}/cryptocurrency/info"

# For communication with hd wallet service
WALLET_SERVICE_URL = env("WALLET_SERVICE_URL", default="")
WALLET_API_KEY_FILE = env("WALLET_API_KEY", default="")
if WALLET_API_KEY_FILE != "":
    with open(WALLET_API_KEY_FILE, "r") as f:
        WALLET_API_KEY = f.read.strip()
else:
    WALLET_API_KEY = ""
