"""
Django settings for community_drf project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import dj_database_url
import os

from datetime import timedelta
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from django.urls import reverse_lazy
from environ import Env
from os.path import join
from pathlib import Path
from urllib.parse import urljoin

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env(DEBUG=(bool, False))

# Take environment variables from .env file
Env.read_env(os.path.join(Path(BASE_DIR).parent, ".env"))

SECRET_KEY = env("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

X_FRAME_OPTIONS = "SAMEORIGIN"

SILENCED_SYSTEM_CHECKS = ["security.W019"]

# Application definition

# Manually setting SCRIPT_NAME in urls because
# FORCE_SCRIPT_NAME doesn't work on admin urls
SCRIPT_NAME = env("DJANGO_SCRIPT_NAME", default="")

SITE_ID = 2

ROOT_URLCONF = "config.urls"

ASGI_APPLICATION = "config.asgi.application"

WSGI_APPLICATION = "config.wsgi.application"

DJANGO_APPS = (
    "daphne",
    "unfold",
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
)

THIRD_PARTY_APPS = (
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.telegram",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "django_filters",
    "django_rq",
    "drf_spectacular",
    "channels",
)

LOCAL_APPS = (
    "main",
    "api",
    "authentication",
    "chat",
    "socialaccounts",
    "users",
    "infocore",
    "messagecore",
    "newscore",
    "tradecore",
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = (
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
)

DATABASES = {
    "default": dj_database_url.config(
        default=env("COMMUNITY_DB_URL"), conn_max_age=600
    ),
    "newscore": dj_database_url.config(
        default=env("NEWSCORE_DB_URL"), conn_max_age=600
    ),
    "messagecore": dj_database_url.config(
        default=env("MESSAGECORE_DB_URL"), conn_max_age=600
    ),
}

DATABASE_ROUTERS = ["config.dbrouter.DBRouter"]

MONGODB = {
    "HOST": env("MONGODB_HOST", default="mongodb"),
    "PORT": env.int("MONGODB_PORT", default=27017),
    "USERNAME": env("MONGODB_USERNAME", default=""),
    "PASSWORD": env("MONGODB_PASSWORD", default=""),
}

MONGO_CHAT_DB = "ACW_USER_CHAT"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_DB_URL", default="redis://localhost:6379"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "default",
    },
}

RQ_SHOW_ADMIN_LINK = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": env(
                        "REDIS_DB_URL",
                        default="redis://localhost:6379",
                    ),
                    "client_name": "django-channels",
                }
            ],
        },
    },
}

REDIS_CHAT_BLOCKLIST_KEY = "acw:user:blocklist"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False,
    "JWT_AUTH_RETURN_EXPIRATION": True,
    "JWT_AUTH_COOKIE": "drf-auth",
    "JWT_AUTH_REFRESH_COOKIE": "drf-refresh",
    "USER_DETAILS_SERIALIZER": "users.serializers.UserSerializer",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# django-allauth config
ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"

ACCOUNT_AUTHENTICATION_METHOD = "username_email"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,
    },
}

# spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Arbitrage Community APIs",
    "DESCRIPTION": "List of all available APIs in Arbitrage Community",
    "VERSION": "1.0.0",
    # 'AUTHENTICATION_WHITELIST': [
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    #     'rest_framework.authentication.SessionAuthentication'
    # ],
    "SERVE_PERMISSIONS": [
        "lib.permissions.IsDjangoAdmin" or "lib.permissions.IsACWAdmin"
    ],
    "SERVE_INCLUDE_SCHEMA": False,
    "SORT_OPERATION_PARAMETERS": False,
    "EXTENSIONS_ROOT": {
        "x-tagGroups": [
            {
                "name": "AUTHENTICATION AND AUTHORIZATION",
                "tags": ["Auth"],
            },
            {
                "name": "CHAT",
                "tags": ["PastChatMessages", "RandomUsername"],
            },
            {
                "name": "USER",
                "tags": ["User", "UserProfile", "UserBlocklist", "UserFavoriteAssets"],
            },
            {
                "name": "TRADE CORE",
                "tags": ["Node", "TradeConfig", "Trade"],
            },
            {
                "name": "MESSAGE CORE",
                "tags": ["Message"],
            },
            {
                "name": "INFO CORE",
                "tags": [
                    "Asset",
                    "Dollar",
                    "FundingRate",
                    "Kline",
                    "MarketCodes",
                    "WalletStatus",
                ],
            },
            {
                "name": "MESSAGE CORE",
                "tags": ["Message"],
            },
            {
                "name": "NEWS CORE",
                "tags": ["Announcements", "News", "SNS Posts"],
            },
        ],
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.normpath(os.path.join(os.path.dirname(BASE_DIR), "static"))

STATIC_URL = urljoin(SCRIPT_NAME, "static/")

STATICFILES_DIRS = []

MEDIA_ROOT = join(os.path.dirname(BASE_DIR), "media")

MEDIA_URL = urljoin(SCRIPT_NAME, "media/")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": STATICFILES_DIRS,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

FIXTURE_DIRS = [os.path.normpath(os.path.join(os.path.dirname(BASE_DIR), "fixtures"))]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("ko", _("Korean")),
]

LOCALE_PATHS = [
    join(Path(BASE_DIR).parent.absolute(), "locale"),
]


UNFOLD = {
    "SITE_TITLE": "Django Admin",
    "SITE_HEADER": "Django Admin",
    "SITE_URL": "/",
    "SITE_SYMBOL": "settings",  # symbol from icon set
    # "LOGIN": {
    #     "image": lambda r: static("sample/login-bg.jpg"),
    # },
    # "STYLES": [
    #     lambda request: static("css/style.css"),
    # ],
    # "SCRIPTS": [
    #     lambda request: static("js/script.js"),
    # ],
}

UNFOLD = {
    "SITE_TITLE": None,
    "SITE_HEADER": None,
    "SITE_URL": "/",
    "SITE_LOGO": {
        "light": lambda request: static("logo-light.svg"),  # light mode
        "dark": lambda request: static("logo-dark.svg"),  # dark mode
    },
    "SITE_SYMBOL": "tune",  # symbol from icon set
    "SHOW_HISTORY": False,  # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True,  # show/hide "View on site" button, default: True
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("ACW"),
                "separator": True,  # Top border
                "items": [
                    # {
                    #     "title": _("Dashboard"),
                    #     "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                    #     "link": reverse_lazy("admin:index"),
                    #     "badge": "sample_app.badge_callback",
                    #     "permission": lambda request: request.user.is_superuser,
                    # },
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": _("User Management"),
                        "icon": "supervisor_account",
                        "link": reverse_lazy("admin:users_usermanagement_changelist"),
                    },
                    {
                        "title": _("User Blocklist"),
                        "icon": "person_off",
                        "link": reverse_lazy("admin:users_userblocklist_changelist"),
                    },
                ],
            },
            {
                "title": _("CORE"),
                "separator": True,
                "items": [
                    {
                        "title": _("Market Codes"),
                        "icon": "sync_alt",
                        "link": reverse_lazy("admin:infocore_marketcode_changelist"),
                    },
                    {
                        "title": _("Nodes"),
                        "icon": "dns",
                        "link": reverse_lazy("admin:tradecore_node_changelist"),
                    },
                    {
                        "title": _("Trade Config Allocations"),
                        "icon": "add_chart",
                        "link": reverse_lazy(
                            "admin:tradecore_tradeconfigallocation_changelist"
                        ),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "outgoing_mail",
                        "link": reverse_lazy("admin:messagecore_message_changelist"),
                    },
                ],
            },
            {
                "title": _(""),
                "separator": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "groups_2",
                        "link": reverse_lazy(
                            "admin:authentication_proxygroup_changelist"
                        ),
                    },
                    {
                        "title": _("Roles"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:users_userrole_changelist"),
                    },
                    {
                        "title": _("API Permissions"),
                        "icon": "http",
                        "link": reverse_lazy("admin:api_permission_changelist"),
                    },
                ],
            },
        ],
    },
}


# CoinMarketCap
COINMARKETCAP_API_KEY = env("COINMARKETCAP_API_KEY")
COINMARKETCAP_API_URL = "https://pro-api.coinmarketcap.com/v2"
COINMARKETCAP_CRYPTO_INFO_API = f"{COINMARKETCAP_API_URL}/cryptocurrency/info"
