# Generated by Django 4.2.11 on 2024-03-12 03:15

from django.db import migrations


def migrate_marketcodeservices_to_marketcodecombinations(apps, schema_editor):
    """
    We can't import the Node model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Node = apps.get_model("tradecore", "Node")
    EnabledMarketCodeCombination = apps.get_model(
        "tradecore", "EnabledMarketCodeCombination"
    )
    MarketCode = apps.get_model("infocore", "MarketCode")

    for node in Node.objects.all():
        for market_code_service in node.market_code_services.all():
            target = MarketCode.objects.get(id=market_code_service.target.id)
            origin = MarketCode.objects.get(id=market_code_service.origin.id)

            try:
                market_code_combination = EnabledMarketCodeCombination.objects.get(
                    target=target, origin=origin
                )
            except EnabledMarketCodeCombination.DoesNotExist:
                market_code_combination = EnabledMarketCodeCombination.objects.create(
                    target=target, origin=origin, trade_support=False
                )

            node.market_code_combinations.add(market_code_combination)

        node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tradecore", "0007_enabledmarketcodecombination_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_marketcodeservices_to_marketcodecombinations),
        migrations.DeleteModel(
            name="NodeMarketCodeService",
        ),
    ]
