# Generated by Django 4.2.11 on 2024-12-13 10:20

import coupon.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                db_index=True,
                default=coupon.models.short_code_generator,
                max_length=20,
                unique=True,
            ),
        ),
    ]
