# Generated by Django 4.2.11 on 2024-05-16 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeelevel",
            name="fee_level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
