# Generated by Django 4.2.11 on 2024-12-05 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fee", "0002_alter_userfeelevel_fee_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feerate",
            name="level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="feerate",
            name="rate",
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name="userfeelevel",
            name="fee_level",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
