# Generated by Django 4.2.4 on 2023-09-07 09:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authtoken", "0003_tokenproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyGroup",
            fields=[],
            options={
                "verbose_name": "Group",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="ProxyToken",
            fields=[],
            options={
                "verbose_name": "Token",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authtoken.token",),
        ),
    ]
